### ISSUE TITLE
Not one command?

### ISSUE THREAD

**Issue by ASnow** [sandrew/from-scratch#2]
Should I install some ruby version with gem command(rvm) before start.
So we duplicates our actions?

**Comment by ASnow** [comment]
Isn't easy

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
sudo apt-get install curl
\curl -sSL https://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm install 2.2.4
sudo apt-get install build-essential
sudo apt-get install clang
sudo apt-get install cmake
rvm requirements
sudo apt-get install libgmp-dev
gem install bundler

**Comment by sandrew** [comment]
@ASnow
RVM is installed user-wide for `deploy` user with MRI 2.2.4. You should not.
